name: 'price_intelligence'
version: '1.0.0'
profile: 'price_intelligence'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  price_intelligence:
    staging:
      +materialized: view
    cleaned:
      +materialized: table
    aggregated:
      +materialized: table