version: 2
models:
  - name: mart_analysis_full
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: price
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
  - name: mart_retailer_comparison
    columns:
      - name: avg_price
        tests:
          - not_null