# ─────────────────────────────────────────
# STREAMLIT APP SERVICE
# ─────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: price-intelligence-app
  namespace: default
spec:
  selector:
    app: price-intelligence-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer

---
# ─────────────────────────────────────────
# NIFI SERVICE
# ─────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: nifi
  namespace: default
spec:
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: ClusterIP

---
# ─────────────────────────────────────────
# PROMETHEUS SERVICE
# ─────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: default
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP

---
# ─────────────────────────────────────────
# GRAFANA SERVICE
# ─────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: default
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer